<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.hb0730</groupId>
    <artifactId>zoom-dev</artifactId>
    <version>${version}</version>
    <packaging>pom</packaging>

    <properties>
        <version>1.0.0-SNAPSHOT</version>
        <java.version>17</java.version>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <modules>
        <!-- 基础设施-->
        <module>BASIC</module>
        <!-- 基础模块-->
        <module>ENV</module>
        <!-- 网关模块-->
        <module>APP</module>

        <!-- 服务模块-->
        <module>APP-P1</module>
        <!--语录-->
        <module>APP-GOROKU</module>
        <!--Nav-->
        <module>APP-NAV</module>
        <!--Resume-->
        <module>APP-RESUME</module>
        <!--Domain-->
        <module>APP-DOMAIN</module>
        <!-- 诗词-->
        <module>APP-POETRY</module>
    </modules>

    <!--    <build>-->
    <!--        <plugins>-->
    <!--            &lt;!&ndash; 统一版本号插件 &ndash;&gt;-->
    <!--            <plugin>-->
    <!--                <groupId>org.codehaus.mojo</groupId>-->
    <!--                <artifactId>flatten-maven-plugin</artifactId>-->
    <!--                <version>1.7.0</version>-->
    <!--                <configuration>-->
    <!--                    <updatePomFile>true</updatePomFile>-->
    <!--                    <flattenMode>oss</flattenMode>-->
    <!--                    <pomElements>-->
    <!--                        <parent>expand</parent>-->
    <!--                        <properties>keep</properties>-->
    <!--                    </pomElements>-->
    <!--                </configuration>-->
    <!--                <executions>-->
    <!--                    <execution>-->
    <!--                        <id>flatten</id>-->
    <!--                        <phase>process-resources</phase>-->
    <!--                        <goals>-->
    <!--                            <goal>flatten</goal>-->
    <!--                        </goals>-->
    <!--                    </execution>-->
    <!--                    <execution>-->
    <!--                        <id>flatten-clean</id>-->
    <!--                        <phase>clean</phase>-->
    <!--                        <goals>-->
    <!--                            <goal>clean</goal>-->
    <!--                        </goals>-->
    <!--                    </execution>-->
    <!--                </executions>-->
    <!--            </plugin>-->
    <!--        </plugins>-->
    <!--    </build>-->
</project>
